xs_dj/dj02/urls.py
#!/usr/bin/env python
#coding:utf-8

from django.conf.urls import  url
import  views
urlpatterns = [
    url(r'index/',views.index,name="index"),
    url(r'login/', views.login, name="login"),
    url(r'asset_allocate/', views.assets, name="assets"),
    url(r'report/', views.report, name="report"),
    url(r'add/([0-9]{2})',views.add,name="add"),
    url(r'delete/',views.delete,name="delete"),
    url(r'modify',views.modify,name="modify"),
    url(r'select/',views.select,name="select"),
    url(r'formget/',views.formget,name="formget"),
]

xs_dj/xs_dj/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from dj02 import  urls
import  dj02
import  myarticle
from myarticle import  myarticle_urls
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dj02/',include(dj02.urls,namespace="dj02")),
    url(r'^myarticle/', include(myarticle.myarticle_urls, namespace="myarticle")),
    url(r'ckeditor/',include('ckeditor_uploader.urls')),
]

xs_dj/dj02/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django import  forms
# Create your models here.

class userlogin(models.Model):
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=256)
    create_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return  self.username

class assets_list(models.Model):
    server_name = models.CharField(max_length=50,verbose_name="服务名")
    server_IP = models.GenericIPAddressField(verbose_name="服务器地址")
    cpu = models.CharField(max_length=10,verbose_name="cpu")
    mem = models.CharField(max_length=20,verbose_name="内存")
    system = models.CharField(max_length=20,verbose_name="操作系统")
    region = models.CharField(max_length=30,verbose_name="机房区域")
    create_date = models.DateTimeField(verbose_name="上架日期")
    remarks = models.TextField(max_length=200,verbose_name="备注")

    def __unicode__(self):
        return  self.server_name

class uaseradmin(models.Model):
    name = models.CharField(max_length=30)
    gender = models.CharField(max_length=1,choices=((1,"man"),(2,"women"),(3,"zhong")))

    def __unicode__(self):
        return self.name

class serveradmin(models.Model):
    user = models.CharField(max_length=30)
    level = models.CharField(max_length=30)

    def __unicode__(self):
        return  self.user

class server(models.Model):
    name = models.CharField(max_length=30)
    IP = models.GenericIPAddressField()
    grade = models.ForeignKey(serveradmin)

    def __unicode__(self):
        return  self.name

# class UploadFileForm(forms.Form):
#     title = forms.CharField(max_length=50)
#     file = forms.FileField()
#
#     def __unicode__(self):
#         return  self.title

class Book(models.Model):
    name = models.CharField(max_length=30)
    price = models.IntegerField()
    pub_date = models.DateTimeField()
    author = models.ManyToManyField("Author")

    def __unicode__(self):
        return  self.name

class Author(models.Model):
    name = models.CharField(max_length=30)
    age = models.IntegerField()

    def __unicode__(self):
        return  self.name

xs_dj/dj02/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render,redirect,HttpResponse
from auth_secret.user_secret import usersecret
from models import userlogin,assets_list,server,uaseradmin,serveradmin,Book,Author
import  json
import  datetime
from datetime import  date
from django.db.models import  Q,Avg,Max,Min,Count,Sum
from django import  forms
import  os
import  chardet
from django.contrib.auth.models import User
from django.forms import  ModelForm
from django.contrib.sessions.middleware import  SessionMiddleware
from django.contrib.sessions.models import  Session
# Create your views here.
from  django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_GET,require_http_methods,require_POST,require_safe
# @csrf_exempt
def index(request):
    now = datetime.datetime.now()
    List = [i for i in range(10)]
    Dict = {i:i for i in range(10)}
    myfirstonetest = "aaaaaaaaaa"
    testdict = {"num":10,"page":"my name is page","python":"python","current_date":now,"def":""}
    return  render(request,'dj02/index1.html',locals())

class CJSONEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj,datetime.datetime):
            return obj.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(obj,date):
            return obj.strftime('%Y-%m-%d')
        else:
            return json.JSONEncoder.default(self,obj)

# @csrf_exempt
# @require_POST
def login(request):
    if request.method == "POST":
        username = request.POST.get('username',None)
        password = request.POST.get('password',None)
        print request.session
        request.session[password] = password
        if username and password:
            password = usersecret(password)
            # userlogin.objects.create(username=username, password=password)
            count = userlogin.objects.filter(username=username,password=password)
            print count
            if count:
                # array = userlogin.objects.all().values("id","username","password","create_date")
                # array = list(array)
                # for i in array:
                #     print i.username,i.password, i.create_date
                # array_dic = {"array":array}
                # return  HttpResponse(json.dumps(array,cls=CJSONEncoder))
                print "ok"
                return redirect('/dj02/index',permanent=True)
            else:
                ret = {"result":"抱歉您的用户名不存在或密码不正确"}
                # return HttpResponse(json.dumps(ret))
                return render(request,'dj02/login.html',ret)
        else:
            ret = {"us_result":"请输入用户名和密码"}
            return  render(request,'dj02/login.html',ret)
    # formtest = UploadFileForm()
    # formtest = ContactForm()
    return  render(request, 'dj02/login.html')

def assets(request):
    assets_data = assets_list.objects.all()
    return render(request,'dj02/assets.html',{"assets_list":assets_data})

def report(request):
    return  render(request,'dj02/report.html')

def add(request,num):
    # example = assets_list(server_name="edi1",server_IP="172.16.1.17",cpu="4",mem="8G",
    #                       system="centos7.1",region="广东电信",create_date="2018-01-09",remarks="")
    # example.save()
    # for i in request.POST:
    #     assets_list.objects.create(server_name=i.server_name,server_IP=i.server_IP,cpu=i.cpu,mem=i.mem,system=i.system,
    #                                region=i.region,create_date=i.create_date,remarks=i.remarks)
    # obj1 = Book(name="openstack",price="45",pub_date="2016-02-08")
    # obj2 = Book(name="docker", price="36", pub_date="2016-02-08")
    # Book.objects.create(name="python",price="38",pub_date="2015-01-22")
    # Author.objects.create(name="while",age=35)
    # Author.objects.create(name="django", age=36)
    # Author.objects.create(name="for", age=30)
    # Author.objects.create(name="while", age=29)
    # data = Book.objects.filter(author__name="while").values("name","price")
    # print data
    # obj = Author.objects.filter(name="head")
    # Book.objects.get(name="php").author.add(*obj)
    # Book.objects.get(name="python").author.add(*(Author.objects.all()))
    # obj = Book.objects.filter(name="php").values("name","price","author__name","author__book__name")
    # print obj
    # obj = Book.objects.filter(Q(name="python") & Q(author__name="head"))
    # obj = Book.objects.get(name="python").author.filter(name="head").delete()
    # 查所有老师分别所出书籍的总价
    obj1 = Book.objects.values("author__name").annotate(names=Sum("price"))
    print obj1
    # 查所有老师所出书籍最贵的书
    obj2 = Book.objects.values("author__name").annotate(names=Max("price"))
    print obj2
    # 查询所有老师所出书的平均价格
    obj3 = Author.objects.values("name").annotate(names=Avg("book__price"))
    print obj3
    # 查询while老师和head老师所出书籍总数
    obj4 = Author.objects.filter(Q(name="while") | Q(name="head")).aggregate(Count("book__name"))
    print obj4
    return HttpResponse("添加成功")

def delete(request):
    # servername = request.POST.get("server_name",None)
    assets_list.objects.filter(id=1).delete()
    return HttpResponse("删除成功")

# @require_POST
def modify(request):
    # modi_data = assets_list.objects.get(server_name="精灵")
    # modi_data.cpu = 12
    # modi_data.save()
    # modi_data.delete()
    # assets_list.objects.filter(server_name="精灵3").update(cpu="16")
    # search = assets_list.objects.filter(server_name__startswith="精灵")[0].server_name
    # print search
    return HttpResponse("修改成功")

def select(request):
    # relate_select = server.objects.filter(grade__user="admin").delete()
    # print relate_select
    # rever_select = serveradmin.objects.filter(server__name="cm1").values("user","level")
    # print rever_select
    # morefilter = serveradmin.objects.filter(server__name="cm1").filter(server__IP="172.16.1.11")
    # print morefilter
    # orselect = server.objects.filter(Q(name="cm1")|Q(name="edi1")).values("name")
    # print orselect
    # copytable = serveradmin(user="test",level="普通用用户")
    # copytable.save()
    # copytable.pk = None
    # copytable.save()
    # copytable = serveradmin.objects.get(user="root")
    # data = copytable.server_set.all()
    # print data
    # print copytable.server_set.count()
    print request.session["123456"]
    avg = server.objects.all().aggregate(Avg("grade"),Max("grade"),Min("grade"))
    print avg
    data = server.objects.filter(name="cm1").values("name","IP","grade__user","grade__level")
    print data
    print avg.get("grade__avg")
    return  redirect('/dj02/asset_allocate')

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)
class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

def formget(request):
    print request.FILES.get("test")
    obj = request.FILES.get("test")
    print obj.size
    # print obj.name
    with open(os.path.join(os.path.dirname(__file__),"{}".format(obj)),"wb") as file:
        for i in obj.chunks():
            print "ok"
            file.write(i)
    # form = UploadFileForm(request.POST, request.FILES)

    return  redirect('/dj02/asset_allocate')

xs_dj/dj02/templates/dj02/assets.html
{% extends 'dj02/base.html' %}
{% load staticfiles %}

{% block page_display %}
    <form class="form-inline" action="{% url "dj02:formget" %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <a href="{% url "dj02:add" 22 %}"><button type="button" class="btn btn-primary  active" id="add">增加数据</button></a>
        <a href="{% url "dj02:delete" %}"><button type="button" class="btn btn-primary  active" id="delete">删除数据</button></a>
        <a href="{% url "dj02:modify" %}"><button type="button" class="btn btn-primary  active">修改数据</button></a>
        <a href="{% url "dj02:select" %}"><button type="button" class="btn btn-primary  active">查询数据</button></a>
        <div class="form-group">
            <input type="file" id="exampleInputFile" name="test"><button type="submit" class="btn">上传</button>
        </div>
    </form>
    <table class="table">
        <tr>
            <td>序号</td>
            <td>服务名</td>
            <td>IP地址</td>
            <td>cpu</td>
            <td>内存</td>
            <td>操作系统</td>
            <td>上架日期</td>
            <td>机房区域</td>
            <td>备注</td>
        </tr>
        {% for i in assets_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ i.server_name }}</td>
                <td>{{ i.server_IP }}</td>
                <td>{{ i.cpu }}</td>
                <td>{{ i.mem }}</td>
                <td>{{ i.system }}</td>
                <td>{{ i.create_date |date:"Y-m-d H:m:s" }}</td>
                <td>{{ i.region }}</td>
                <td>{{ i.remarks }}</td>
            </tr>
        {% endfor %}
    </table>

    <script>
        function get_browser() {

           var N = navigator.appName, ua =navigator.userAgent, tem;

           var M =ua.match(/(opera|chrome|safari|firefox|msie)\/?\s*(\.?\d+(\.\d+)*)/i);

           if (M && (TEM = ua.match(/version\/([\.\d]+)/i)) != null) M[2] =tem[1];

           M = M ? [M[1], M[2]] : [N, navigator.appVersion, '-?'];

           return M[0];

       }

       function get_browser_version() {

           var N = navigator.appName, ua = navigator.userAgent, tem;

           var M = ua.match(/(opera|chrome|safari|firefox|msie)\/?\s*(\.?\d+(\.\d+)*)/i);

           if (M && (tem = ua.match(/version\/([\.\d]+)/i)) != null) M[2] =tem[1];

           M = M ? [M[1], M[2]] : [N, navigator.appVersion, '-?'];

           return M[1];

       }

       var browser = get_browser();

       var browser_version = get_browser_version();

       var br_detect = 0; //default to run

       if (browser == 'MSIE') {

           if (parseInt(browser_version) < 9) {

                var br_detect = 1; //not runthe status js

           }

        } //end if browser



                   //setJS controller variable for speed monitor plugin

                   var BoomRunMark = 0; //0 = enable ,  1=disable

                   var BoomKickStartMark = 5; // run the collect plugin when random num < 5

                   var RandomNumber = Math.floor((Math.random() * 10) + 1);

                   if(br_detect == 0) {

                            imgLoadBeginTime= new Date();



                   }

                   //console.log('randomnumber :'+ RandomNumber);

       if (br_detect == 0) {

                     if (BoomRunMark == 0){

                            if(RandomNumber  < BoomKickStartMark ){

                                     BOOMR.init({

                                               beacon_url:"http://perf.che168.com/pv_perf.php",

                                               BW:{ enabled: false },

                                               RT:{

                                                        cookie:'CHE168-RT'

                                               }

                                     });

                            }//endRandomNumber check

                     }// end BoomRunMark check

       }//end if br_detect

    </script>
{% endblock %}

xs_dj/dj02/templates/dj02/base.html
<!DOCTYPE html>
{% load staticfiles %}
{#{% load my_tags %}#}
<html lang="en">
{% block head %}
<html lang="en">
<html lang="zh-CN" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>xueshen_dj01</title>
    <!--<link type="text/css" rel="stylesheet" href="../bootstrap/dist/css/bootstrap.min.css">-->
    <!--<link type="text/css" rel="stylesheet" href="../static/css/index.css">-->

    <link type="text/css" rel="stylesheet" href="{% static "dj02/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link type="text/css" href="{% static "dj02/css/base.css" %}" rel="stylesheet" >
</head>
{% endblock %}
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <!--居中展示-->
        <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
            <div class="row">
                <div class="col-md-2 col-lg-2">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <button type="button" class="btn btn-default navbar-btn nav-buttom-color nav-img-size">CMDB</button>
                    </div>
                </div>
                <div class="col-md-8 col-lg-8">
                    <div class="collapse navbar-collapse navbar-left" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav ">
                            <li class="active"><a href="#">首页 <span class="sr-only">(current)</span></a></li>
                            <li><a href="#">资产配置</a></li>
                            <li><a href="#">服务应用</a></li>
                            <li><a href="#">故障记录</a></li>
                            <li><a href="#">报表</a></li>
                            <li><a href="#">联系我们</a></li>
                        </ul>
                    </div>
                </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
{#                <div class="col-md-2">#}
                    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-2">
                        <ul class="nav navbar-nav ">
                            <li><a href="{% url "dj02:login" %}">登录/注销</a></li>
                            <li><a href="#">建议</a></li>
                        </ul>
                    </div>
{#                </div><!-- /.navbar-collapse -->#}
            </div>
        </div><!-- /.container-fluid -->
    </nav>
    <div class="container top-indent ">
        <div class="row">
            <div class="col-md-2 navbar-inverse">
{#                <div class="container ">#}
{#                    <div class="row">#}
{#                        <div class="col-md-3">#}
{#                            <div class="container-fluid">#}
{#                                <div class="row">#}
{#                                    <div class="col-md-12">#}
                                        <ul class="nav nav-list">
                                            <li class="nav-header">Components
                                                <span >列表标题</span>
                                            </li>
                                            <li class="active">
                                                <a href="{% url "dj02:index" %}">
                                                    <i></i>首页</a>
                                            </li>
                                            <li>
                                                <a href="{% url "dj02:assets" %}">
                                                    <i></i>资产配置</a>
                                            </li>
                                            <li>
                                                <a href="{% url "dj02:report" %}">
                                                    <i></i>报表</a>
                                            </li>
                                            <li class="nav-header">
                                                服务列表
                                            </li>
                                            <li>
                                                <a href="javascript:;">cm</a>
                                                <ul>
                                                    <li>
                                                        <a href="">
                                                            <span></span>cm1
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="">
                                                            <span ></span>cm2
                                                        </a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li>
                                                <a href="#">edi</a>
                                            </li>
                                            <li class="divider">
                                            </li>
                                            <li class="navbar-header">
                                                帮助
                                            </li>
                                            <li>
                                                <a href="#"></a>
                                            </li>
                                        </ul>
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                        <div class="col-md-9">#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
            </div>
            <div class="col-md-10 ">
                {% block page_display %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

xs_dj/dj02/templates/dj02/index1.html
<!DOCTYPE html>
{% extends "./base.html" %}
{% load staticfiles %}
{% load my_tags %}
{% block page_display %}
    <div>
        ddddd<br>
        请求方法：{{ request.method }}<br>
        主路径：{{ request.path }} </br>
        全路径：{{ request.get_full_path }}</br>
        current_time：{{ now }}
    </div>
    <div>
        {% for i in List %}
            {% if forloop.first %}
                <div style="color: red">{{ forloop.counter }}:{{ i }}</div>
            {% else %}
                {{ forloop.counter }}:{{ i
                    }}
            {% endif %}
        {% endfor %}</br>
        自定义两个参数传递：
        {% for i in List %}
            {{ i | DataAdd:1 }}
        {% endfor %}<br>
        {% for i in Dict %}
            {{ i }}:{{ Dict.i }}</br>
        {% endfor %}
        {% verbatim %}
            {{ ceshi }}
        {% endverbatim %}</br>
        {% with firsst=myfirstonetest %}
            别名：{{ firsst }}
        {% endwith %}
    </div>
    <div>
        过滤器：<br>
        {{ testdict.num | add:20 }}<br>
        {{ testdict.page | cut:"name" }}<br>
        {{ testdict.python | capfirst }}<br>
        {{ testdict.current_date |date:"Y-m-d" }}<br>
        {{ testdict.def |default:"测试" }}<br>
        自定义多个参数传递：{% MultiTags 1 2 3 %}
    </div>
{% endblock %}

xs_dj/dj02/templates/dj02/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<html lang="zh-CN" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>xueshen_dj01</title>
    <!--<link type="text/css" rel="stylesheet" href="../bootstrap/dist/css/bootstrap.min.css">-->
    <!--<link type="text/css" rel="stylesheet" href="../static/css/index.css">-->

    <link type="text/css" rel="stylesheet" href="{% static "dj02/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link type="text/css" rel="stylesheet" href="{% static "dj02/css/login.css" %}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12 "></div>
            <img src="{% static "dj02/img/avatar3.jpg" %}" class="img-responsive img-circle center-block img-size" alt="Responsive image">
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3">
                <form class="form-inline" action="{% url 'dj02:login' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group has-success has-feedback " id="user">
                        <label class="control-label" for="inputSuccess4">UserName：</label>
                        <div class="input-group input-group-lg">
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-user"></i>
                            </span>
                            <input type="text" class="form-control user " id="inputSuccess4" aria-describedby="inputSuccess4Status" name="username">
                        </div>
                        <div class="input-group input-group-sm btn-block" style="color:red;"><span class="btn-block  text-center">{{ us_result }}</span></div>
                        <span  aria-hidden="true"></span>
                        <span id="inputSuccess4Status" class="sr-only">(success)</span>
                    </div>
                    <div class="form-group has-success has-feedback" id="passwd">
                        <label class="control-label" for="inputGroupSuccess3">PassWord：</label>
                        <div class="input-group input-group-lg ">
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-lock"></i>
                            </span>
                            <input type="password" class="form-control passwd" id="inputGroupSuccess3" aria-describedby="inputGroupSuccess3Status" name="password">
                        </div>
                        <span  aria-hidden="true"></span>
                        <span id="inputGroupSuccess3Status" class="sr-only">(success)</span>
                    </div>
                    <div class="form-group has-success has-feedback text-center btn-group-lg " id="login">
                        <input class="btn btn-primary btn-block " type="submit" value="login" id="submitdata">
                    </div>
                    <div class="input-group input-group-sm btn-block" style="color:red;"><span class="btn-block text-center">{{ result }}</span></div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">

            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">

            </div>
        </div>
    </div>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="table-responsive">
                    <table class="table">
                        <tr class="table-data">
                            <td>ID</td>
                            <td>用户名</td>
                            <td>密码</td>
                            <td>创建日期</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        {{ form }}
    </div>
    <script type="text/javascript">
{#        $(function () {#}
{#            $.ajaxSetup({#}
{#                headers: { "X-CSRFToken": getCookie("csrftoken") }#}
{#            });#}
{#        });#}
{#        $('#submitdata').click(function () {#}
{#            var username = $('.user').val()#}
{#            var password = $('#inputGroupSuccess3').val()#}
{#            if (username == "") {#}
{#                var count = $('#inputSuccess4').parent().next("div").hasClass("input-group-sm")#}
{#                if (!count) {#}
{#                    $('.user').parent().after('<div class="input-group input-group-sm btn-block" style="color:red;"><span class="btn-block  text-center">请输入用户名</span></div>')#}
{#                }#}
{#            }#}
{#            if (password == ""){#}
{#                var count = $('#inputGroupSuccess3').parent().next("div").hasClass("input-group-sm")#}
{#                if (!count) {#}
{#                    $('.passwd').parent().after('<div class="input-group input-group-sm btn-block" style="color:red;"><span class="btn-block text-center">请输入密码</span></div>')#}
{#                }#}
{#            }#}
{#            $.ajax({#}
{#                type:"POST",#}
{#                url:"/dj02/login/",#}
{#                data:{"username":username,"password":password},#}
{#                success:function(args) {#}
{#                    args = jQuery.parseJSON(args);#}
{#                    console.log(args)#}
{#                    console.log(args.length)#}
{#                    if (args.length > 1) {#}
{#                        for (var i=0;i<args.length;i++) {#}
{#                            $('.table-data').after('<tr><td>'+args[i].id+'</td><td>'+args[i].username+'</td><td>'+args[i].password+'</td><td>'+args[i].create_date+'</td></tr>')#}
{#                        }#}
{#                    }#}
{#                    else {#}
{#                        $('#submitdata').parent().after('<div class="input-group input-group-sm btn-block" style="color:red;"><span class="btn-block text-center">'+args.result+'</span></div>')#}
{#                        setTimeout(function () {#}
{#                            var count = $('#submitdata').parent().next("div").hasClass("input-group-sm")#}
{#                            if (count) {#}
{#                                $('#submitdata').parent().next("div").remove()#}
{#                            }#}
{#                        },3000)#}
{#                    }#}
{#                }#}
{#            })#}
{#        })#}
        $('#inputSuccess4').focus(function () {
            var count = $('#inputSuccess4').parent().next("div").hasClass("input-group-sm")
            if (count) {
                $('#inputSuccess4').parent().next("div").remove()
            }
            var tips = $('#login').next("div").text()
            if (tips) {
                $('#login').next("div").remove()
            }
        })
        $('#inputGroupSuccess3').focus(function () {
            var count = $('#inputGroupSuccess3').parent().next("div").hasClass("input-group-sm")
            if (count) {
                $('#inputGroupSuccess3').parent().next("div").remove()
            }
            var tips = $('#login').next("div").text()
            if (tips) {
                $('#login').next("div").remove()
            }
        })
{#        $('#submitdata').click(function () {#}
{#            console.log("222")#}
{#            setTimeout(function () {#}
{#                var tips = $('#submitdata').parent().next('div').html()#}
{#                console.log("333")#}
{#                console.log(tips)#}
{#            },1000)#}
{#        })#}
    </script>
</body>
</html>

xs_dj/dj02/templates/dj02/report.html
{% extends 'dj02/base.html' %}