xs_dj/dj02/urls.py
#!/usr/bin/env python
#coding:utf-8

from django.conf.urls import  url
import  views
urlpatterns = [
    url(r'index/',views.index,name="index"),
    url(r'login/', views.login, name="login"),
    url(r'asset_allocate/', views.assets, name="assets"),
    url(r'report/', views.report, name="report"),
    url(r'add/([0-9]{2})',views.add,name="add"),
    url(r'delete/',views.delete,name="delete"),
    url(r'modify',views.modify,name="modify"),
    url(r'select/',views.select,name="select"),
    url(r'formget/',views.formget,name="formget"),
]

xs_dj/xs_dj/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from dj02 import  urls
import  dj02
import  myarticle
from myarticle import  myarticle_urls
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dj02/',include(dj02.urls,namespace="dj02")),
    url(r'^myarticle/', include(myarticle.myarticle_urls, namespace="myarticle")),
    url(r'ckeditor/',include('ckeditor_uploader.urls')),
]

xs_dj/myarticle/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from  ckeditor_uploader.fields import  RichTextUploadingField
# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=32,verbose_name="文章标题")
    author = models.ForeignKey("Author")
    pub_date = models.DateField(verbose_name="发表日期")
    content = RichTextUploadingField(verbose_name="文章内容")
    img = models.ImageField(upload_to="images",verbose_name="文章图片",blank=True)
    dsecription = RichTextUploadingField(verbose_name="文章摘要",blank=True)

    def __unicode__(self):
        return  self.title

class Author(models.Model):
    name = models.CharField(max_length=32,verbose_name="作者姓名")
    email = models.EmailField(verbose_name="作者邮箱")
    age = models.IntegerField(verbose_name="作者年龄",blank=True,null=True)
    gender_typer = (("man",u"男"),("women",u"女"))
    gender = models.CharField(max_length=3,choices=gender_typer,verbose_name="性别",blank=True)
    phone = models.CharField(max_length=32,verbose_name="手机",blank=True)
    address = models.CharField(max_length=128,verbose_name="地址",blank=True)

    photo = models.ImageField(upload_to="images",verbose_name="文件",blank=True)
    description = RichTextUploadingField(verbose_name="描述",blank=True)

    def __unicode__(self):
        return  self.name

class Asset_List(models.Model):
    ip_add = models.GenericIPAddressField(verbose_name="访问地址")
    server_name = models.ForeignKey("Server")
    cpu = models.CharField(max_length=32,verbose_name="CPU核数",blank=True,null=True)
    mem = models.CharField(max_length=32,verbose_name="内存大小",blank=True,null=True)
    hard = models.CharField(max_length=32,verbose_name="硬盘大小",blank=True,null=True)
    region = models.CharField(max_length=32,verbose_name="所在区域")
    position = models.CharField(max_length=128,verbose_name="机房地址")
    cabinet = models.CharField(max_length=64,verbose_name="具体机柜位置")
    shelf_time = models.DateField(verbose_name="上架时间")
    description = models.TextField(verbose_name="备注",blank=True,null=True)

    def __unicode__(self):
        return self.ip_add

class Server(models.Model):

    server_name = models.CharField(max_length=32,verbose_name="服务名称")
    server_port = models.CharField(max_length=16,verbose_name="服务端口")
    access_type = models.CharField(max_length=32,verbose_name="访问类别")
    def __unicode__(self):
        return self.server_name

class Userlogin(models.Model):
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=256)
    email = models.EmailField()
    create_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return  self.username

xs_dj/myarticle/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, HttpResponse
from io import  BytesIO
from models import *
from myarticle.utils.user_secret import usersecret
from template_form import *
from myarticle.utils import create_images
from django.core.paginator import Page,PageNotAnInteger,Paginator,EmptyPage
from utils.base_page import Page_set

def login_Decorator(func):
    def wrapper(request,*args):
        obj = request.session.get("username",None)
        print obj
        if obj:
            return func(request,*args)
        else:
            return redirect('/myarticle/login')
    return wrapper

@login_Decorator
def index(request,index_id=1):
    # 加载首页,获取数据总数
    obj = Article.objects.all().count()
    # print obj
    # 分页实例化
    per_page_item_num = request.session.get("per_page_display_num",None)
    if not per_page_item_num:
        per_page_item_num = 5
    page_set = Page_set(obj,"/myarticle/index/",index_id,per_page_item_num)
    # 获取此页的数据,默认第一页，有带页面参数时才用自带的
    obj = Article.objects.all()[page_set.start_index:page_set.end_index]
    # 获取页码数渲染到前端
    render_page = page_set.page_render
    return render(request,'myarticle/index.html',locals())

def login(request):
    if request.method == "POST":
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        # 获取账号密码的值，首先判断是否非空
        if username and password:
            # 获取前端验证码以及后端创建的验证码保存在session的值是否相同
            session_code = request.session["check_code"]
            web_code = request.POST.get("check_code")
            if session_code.lower() == web_code.lower():
                password = usersecret(password)
                # userlogin.objects.create(username=username, password=password)
                count = Userlogin.objects.filter(username=username, password=password)
                if count:
                    # array = userlogin.objects.all().values("id","username","password","create_date")
                    # array = list(array)
                    # for i in array:
                    #     print i.username,i.password, i.create_date
                    # array_dic = {"array":array}
                    # return  HttpResponse(json.dumps(array,cls=CJSONEncoder))

                    # 添加cookie和session
                    request.session["username"]=password
                    request.session.set_expiry(0)
                    # request.session["per_page_display_num"] = 5
                    # 登录成功删除之前保存的分页数据显示初始值
                    per_page_item_num = request.session.get("per_page_display_num", None)
                    if per_page_item_num:
                        del request.session["per_page_display_num"]
                    return redirect('/myarticle/index', permanent=True)
                else:
                    ret = {"result": "抱歉您的用户名不存在或密码不正确"}
                    return render(request, 'myarticle/login.html', ret)
            return render(request,'myarticle/login.html',{"ret":"验证码不正确"})
        else:
            ret = {"us_result": "请输入用户名和密码"}
            return render(request, 'myarticle/login.html', ret)
    else:
        return render(request, 'myarticle/login.html',locals())

@login_Decorator
def article(request,article_id):
    # 根据id检索文章的各项内容展示 在前端
    obj = Article.objects.filter(id=article_id)
    return render(request,'myarticle/article_display.html',locals())

@login_Decorator
def asset(request,index_id=1):
    # 展示资产列表
    print index_id
    obj = Asset_List.objects.all().count()
    per_page_item_num = request.session.get("per_page_display_num", None)
    if not per_page_item_num:
        per_page_item_num = 6
    print "per_page_display_num:",per_page_item_num
    page_set = Page_set(obj, "/myarticle/asset_list/", index_id,per_page_item_num)
    obj = Asset_List.objects.all()[page_set.start_index:page_set.end_index]
    render_page = page_set.page_render
    return  render(request,'myarticle/asset_list.html',locals())

@login_Decorator
def add_asset(request):
    if request.method == "POST":
        # 提交数据至数据，前提是先验证数据的合法性
        obj = Asset_Form(request.POST)
        if obj.is_valid():
            # 在数据有效的前提下从查询集转换成字典，并去除非post用户填写的数据
            obj = obj.cleaned_data
            obj["server_name_id"]=obj["server_name"]
            del obj["server_name"]
            # Asset_List.objects.create(cpu=obj["cpu"],ip_add=obj["ip_add"],mem=obj["mem"],hard=obj["hard"],
            #                           region=obj["region"],position=obj["position"],cabinet=obj["cabinet"],
            #                           shelf_time=obj["shelf_time"],description=obj["description"],server_name_id=4)
            Asset_List.objects.create(**obj)
            return redirect("/myarticle/asset_list")
        else:

            return render(request, 'myarticle/add _asset.html', locals())
    else:
        obj = Asset_Form()
        # 纯粹的加载一个添加数据的页面
        return  render(request,'myarticle/add _asset.html',locals())

@login_Decorator
def update_asset(request,asset_id):
    if request.method == "POST":
        obj = request.POST
        print obj["csrfmiddlewaretoken"]
        # del  obj["csrfmiddlewaretoken"]
        # request获取到的是查询集，不允许修改，先验证提交数据的合法性
        obj = Asset_Form(obj)
        if obj.is_valid():
            # 清除表单用户填写之外的数据，方便载入数据库，顺便转成字典格式
            obj = obj.cleaned_data
            #由于服务这里是通过外键关联的形式，所以得先获取id才能导入数据
            print obj["server_name"]
            # id = Server.objects.filter(server_name=obj["server_name"]).values_list("id")
            # obj["server_name"] = id
            Asset_List.objects.filter(id=asset_id).update(**obj)
            return redirect("myarticle/asset_list")
        else:
            return render(request, 'myarticle/update_asset.html', locals())
    else:
        #根据访问的id从数据库获取数据
        obj = Asset_List.objects.filter(id=asset_id).first()
        #把数据加载进表单中
        obj = Asset_Form({"ip_add":obj.ip_add,"server_name":obj.server_name,
            "cpu":obj.cpu,"mem":obj.mem,"hard":obj.hard,
            "region":obj.region,"position":obj.position,
            "cabinet":obj.cabinet,"shelf_time":obj.shelf_time,
            "description":obj.description}
        )
        asset_id = {"id":asset_id}
        # 表单数据加载进新的页面中，这样修改数据就是之前的那天数据
        return  render(request,'myarticle/update_asset.html',locals())


def user_register(request):
    if request.method == "GET":
        # 通过form来渲染注册页面
        obj = Register_Form()
        return  render(request,'myarticle/user_register.html',locals())
    else:
        obj = Register_Form(request.POST)
        if obj.is_valid():
            # 首先判断提交注册的有效性，然后来调用其他的方法来判断数据库中数据是否存在
            result = obj.check_username()
            if result == True:
                result = obj.check_two_pwd()
                if result == True:
                    result = obj.check_email()
                    if result == True:
                        obj = obj.cleaned_data
                        del obj["pwd_again"]
                        obj["password"] = usersecret(obj["password"])
                        Userlogin.objects.create(**obj)
                        return redirect('/myarticle/login')
            return render(request, 'myarticle/user_register.html', locals())
        else:
            return  render(request,'myarticle/user_register.html',locals())

def create_code_img(request):
    f = BytesIO() #直接在内存开辟一点空间存放临时生成的图片
    # 调用check_code生成照片和验证码
    img, code = create_images.Create_image()
    request.session['check_code'] = code #将验证码存在服务器的session中，用于校验
    # print request.session["check_code"]
    img.save(f,'PNG') #生成的图片放置于开辟的内存中
    # print f.getvalue()
    return HttpResponse(f.getvalue())  #将内存的数据读取出来，并以HttpResponse返回

def logout(request):
    # 如果存在session_id，则删除此id
    obj = request.session.get("username",None)
    if obj:
        del request.session["username"]
        return  redirect('/myarticle/login')

def pagecache(request):
    per_page_display_num = request.GET["data"]
    url_path =  request.GET["url_path"]
    print per_page_display_num
    request.session["per_page_display_num"] = per_page_display_num
    return  redirect(url_path)

xs_dj/myarticle/templates/myarticle/article_display.html
{% extends 'myarticle/base.html' %}
{% load staticfiles %}
{% block title %}  文章展示 {% endblock %}
{% block mycss %}
    <link type="text/css" href="{% static "myarticle/css/base.css" %}" rel="stylesheet" >
{% endblock %}
{% block content-center %}
    <div class="col-md-7 col-sm-7 col-xs-10 ">
    {% for article in obj %}
        <h3>{{ article.title }}</h3>
        <p style="text-align: right">作者：{{ article.author }}</p>
        {{ article.content|safe }}
        <p style="text-align: right">发表时间：{{ article.pub_date }}</p>
    {% endfor %}
    </div>
{% endblock %}

xs_dj/myarticle/templates/myarticle/base.html
<!DOCTYPE html>
{% load staticfiles %}
{#{% load my_tags %}#}

<html lang="zh-CN" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} 个人博客 {% endblock %}</title>
    <!--<link type="text/css" rel="stylesheet" href="../bootstrap/dist/css/bootstrap.min.css">-->
    <!--<link type="text/css" rel="stylesheet" href="../static/css/index.css">-->
    <link type="text/css" rel="stylesheet" href="{% static "myarticle/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block mycss %}
    <link type="text/css" href="{% static "myarticle/css/base.css" %}" rel="stylesheet" >
    {% endblock %}
    <script src="{% static "myarticle/js/paging.js" %}"></script>
</head>
<body >
    {% block nav-image %}
    <div class="row">
      <div class="col-md-12">
          <img src="{% static "myarticle/image/new_top-min.jpg" %}" class="img-responsive" alt="Responsive image">
      </div>
    </div>
    {% endblock %}
    {% block nav-tag %}
    <nav class="navbar navbar-default ">
      <div class="container-fluid ">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Brand logo</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse " id="bs-example-navbar-collapse-1">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6 col-md-offset-2 ">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="{% url "myarticle:index" %}">首页 <span class="sr-only">(current)</span></a></li>
                            <li><a href="#">文章</a></li>
                            <li><a href="#">经典收录</a></li>
                            <li><a href="#">个人随笔</a></li>
                            <li><a href="#">留言</a></li>
                            <li><a href="#">关于我</a></li>
                        </ul>
                    </div>
                    <div class="">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url "myarticle:login" %}">登录</a></li>
                            <li><a href="{% url 'myarticle:logout' %}">注销</a></li>
                            <li><a href="{% url 'myarticle:register' %}">注册</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    {% endblock %}
    {% block body-content %}
    <div class="container navbgl">
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-8">
                <div class="row text-center">
                    <div class="">
                        <br>
                        <a href="{% url "myarticle:asset_list" %}">资产配置</a>
                    </div>
                </div>
                <div class="row text-center">
                    <div class="">
                        资产配置
                    </div>
                </div>
                {% block content-left %}

                {% endblock %}
            </div>
            {% block content-center %}
            <div class="col-md-7 col-sm-7 col-xs-10 ">
            </div>

            {% endblock %}
            {% block content-right %}
            <div class="col-md-2 col-sm-2 col-xs-8 ">
            </div>
            {% endblock %}
        </div>
    </div>
    {% endblock %}
    {% block body-myself %}
    {% endblock %}
</body>
</html>

xs_dj/myarticle/templates/myarticle/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<html lang="zh-CN" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>xueshen_dj01</title>
    <!--<link type="text/css" rel="stylesheet" href="../bootstrap/dist/css/bootstrap.min.css">-->
    <!--<link type="text/css" rel="stylesheet" href="../static/css/index.css">-->

    <link type="text/css" rel="stylesheet" href="{% static "myarticle/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link type="text/css" rel="stylesheet" href="{% static "myarticle/css/login.css" %}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12 "></div>
            <img src="{% static "myarticle/image/avatar3.jpg" %}" class="img-responsive img-circle center-block img-size" alt="Responsive image">
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3">
                <form class="form-inline" action="{% url 'myarticle:login' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group has-success has-feedback " id="user">
                        <label class="control-label" for="inputSuccess4">UserName：</label>
                        <div class="input-group input-group-lg">
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-user"></i>
                            </span>
                            <input type="text" class="form-control user " id="inputSuccess4" aria-describedby="inputSuccess4Status" name="username" >
                        </div>
                        <div class="input-group input-group-sm btn-block" style="color:red;"><span class="btn-block  text-center">{{ us_result }}</span></div>
                        <span  aria-hidden="true"></span>
                        <span id="inputSuccess4Status" class="sr-only">(success)</span>
                    </div>
                    <div class="form-group has-success has-feedback" id="passwd">
                        <label class="control-label" for="inputGroupSuccess3">PassWord：</label>
                        <div class="input-group input-group-lg ">
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-lock"></i>
                            </span>
                            <input type="password" class="form-control passwd" id="inputGroupSuccess3" aria-describedby="inputGroupSuccess3Status" name="password">
                        </div>
                        <span  aria-hidden="true"></span>
                        <span id="inputGroupSuccess3Status" class="sr-only">(success)</span>
                    </div>
                    <div class="form-group has-success has-feedback input-group-lg">
                        <div class="input-group input-group-lg ">
                            <input type="text" class="form-control " name="check_code" id="check_code" placeholder="请输入验证码" style="width: 140px">
                            <img id="check_code_img" src="{% url 'myarticle:ver_code_display' %}" >
                            <button id="flush" style="font-size: 18px;height: 46px">刷新</button>
                            <span>{{ ret }}</span>
                        </div>
                    </div>
{#                    <br>#}
                    <div class="form-group has-success has-feedback">
                        <label>
                            <input type="checkbox" value="1" name="auto_login"> Remember me
                        </label>

                        <div class="right" style="display: inline-block">
                            <a href="#">忘记密码？</a>
                        </div>
                    </div>
{#                    <br>#}
                    <div class="form-group has-success has-feedback">
                        <span>没有账号？<a href="{% url 'myarticle:register' %}">注册账号</a></span>
                    </div>
                    <div class="form-group has-success has-feedback text-center btn-group-lg " id="login">
                        <input class="btn btn-primary btn-block " type="submit" value="login" id="submitdata">
                    </div>
                    <div class="input-group input-group-sm btn-block" style="color:red;"><span class="btn-block text-center">{{ result }}</span></div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">

            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">

            </div>
        </div>
    </div>
    <br>
    <script type="text/javascript">
{#        $(function () {#}
{#            $.ajaxSetup({#}
{#                headers: { "X-CSRFToken": getCookie("csrftoken") }#}
{#            });#}
{#        });#}
{#        $('#submitdata').click(function () {#}
{#            var username = $('.user').val()#}
{#            var password = $('#inputGroupSuccess3').val()#}
{#            if (username == "") {#}
{#                var count = $('#inputSuccess4').parent().next("div").hasClass("input-group-sm")#}
{#                if (!count) {#}
{#                    $('.user').parent().after('<div class="input-group input-group-sm btn-block" style="color:red;"><span class="btn-block  text-center">请输入用户名</span></div>')#}
{#                }#}
{#            }#}
{#            if (password == ""){#}
{#                var count = $('#inputGroupSuccess3').parent().next("div").hasClass("input-group-sm")#}
{#                if (!count) {#}
{#                    $('.passwd').parent().after('<div class="input-group input-group-sm btn-block" style="color:red;"><span class="btn-block text-center">请输入密码</span></div>')#}
{#                }#}
{#            }#}
{#            $.ajax({#}
{#                type:"POST",#}
{#                url:"/dj02/login/",#}
{#                data:{"username":username,"password":password},#}
{#                success:function(args) {#}
{#                    args = jQuery.parseJSON(args);#}
{#                    console.log(args)#}
{#                    console.log(args.length)#}
{#                    if (args.length > 1) {#}
{#                        for (var i=0;i<args.length;i++) {#}
{#                            $('.table-data').after('<tr><td>'+args[i].id+'</td><td>'+args[i].username+'</td><td>'+args[i].password+'</td><td>'+args[i].create_date+'</td></tr>')#}
{#                        }#}
{#                    }#}
{#                    else {#}
{#                        $('#submitdata').parent().after('<div class="input-group input-group-sm btn-block" style="color:red;"><span class="btn-block text-center">'+args.result+'</span></div>')#}
{#                        setTimeout(function () {#}
{#                            var count = $('#submitdata').parent().next("div").hasClass("input-group-sm")#}
{#                            if (count) {#}
{#                                $('#submitdata').parent().next("div").remove()#}
{#                            }#}
{#                        },3000)#}
{#                    }#}
{#                }#}
{#            })#}
{#        })#}
        $('#inputSuccess4').focus(function () {
            var count = $('#inputSuccess4').parent().next("div").hasClass("input-group-sm")
            if (count) {
                $('#inputSuccess4').parent().next("div").remove()
            }
            var tips = $('#login').next("div").text()
            if (tips) {
                $('#login').next("div").remove()
            }
        })
        $('#inputGroupSuccess3').focus(function () {
            var count = $('#inputGroupSuccess3').parent().next("div").hasClass("input-group-sm")
            if (count) {
                $('#inputGroupSuccess3').parent().next("div").remove()
            }
            var tips = $('#login').next("div").text()
            if (tips) {
                $('#login').next("div").remove()
            }
        })
{#        $('#submitdata').click(function () {#}
{#            console.log("222")#}
{#            setTimeout(function () {#}
{#                var tips = $('#submitdata').parent().next('div').html()#}
{#                console.log("333")#}
{#                console.log(tips)#}
{#            },1000)#}
{#        })#}
        $('#flush').click(function () {
            $('#flush').parent().prev().find('#check_code_img').src += '?';
        })
    </script>
</body>
</html>

xs_dj/myarticle/templates/myarticle/user_register.html
{#<!DOCTYPE html>#}
{% extends 'myarticle/base.html' %}
{% load staticfiles %}
{#<html lang="zh-CN" xmlns="http://www.w3.org/1999/html">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <meta http-equiv="X-UA-Compatible" content="IE=edge">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1">#}
    <title>{% block title %} 用户注册 {% endblock %}</title>
{#    <!--<link type="text/css" rel="stylesheet" href="../bootstrap/dist/css/bootstrap.min.css">-->#}
{#    <!--<link type="text/css" rel="stylesheet" href="../static/css/index.css">-->#}
{#    <link type="text/css" rel="stylesheet" href="{% static "myarticle/css/bootstrap.min.css" %}">#}
{#    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">#}
{#	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>#}
{#	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>#}
{#    <link type="text/css" href="{% static "myarticle/css/base.css" %}" rel="stylesheet" >#}
{#</head>#}
<body>
    {% block nav-tag %}
    {% endblock %}
    {% block body-content %}
    {% endblock %}
    {% block body-myself %}
    <br>
    <div class="container navbgl">
        <div class="row">
            <br>
            <br>
        </div>
        <div class="row">
            <div class="col-md-2 col-sm-2 col-xs-1"></div>
            <div class="col-md-6 col-sm-8 col-xs-10">
                <form class="form-horizontal" action="{% url 'myarticle:register' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="inputUser3" class="col-sm-3 control-label">Username：</label>
                        <div class="col-sm-9">
{#                            <input type="text" class="form-control" id="inputUser3" placeholder="username">#}
                            {{ obj.username }}{{ obj.errors.username.0 }}{{ result.user }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-3 control-label">Enter Pwd：</label>
                        <div class="col-sm-9">
{#                            <input type="password" class="form-control" id="inputPassword3" placeholder="password">#}
                            {{ obj.password }}{{ obj.errors.password.0 }}{{ result.pwd }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEnterPassword3" class="col-sm-3 control-label">Password：</label>
                        <div class="col-sm-9">
{#                            <input type="password" class="form-control" id="inputEnterPassword3" placeholder="enter password">#}
                            {{ obj.pwd_again }}{{ obj.errors.pwd_again.0 }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputemail3" class="col-sm-3 control-label">Email：</label>
                        <div class="col-sm-9">
{#                            <input type="email" class="form-control" id="inputemail3" placeholder="email">#}
                            {{ obj.email }}{{ obj.errors.email.0 }}{{ result.email }}
                        </div>
                    </div>
{#                    <div class="form-group">#}
{#                        <div class="col-sm-offset-3 col-sm-9">#}
{#                            <div class="checkbox">#}
{#                                <label>#}
{#                                    <input type="checkbox"> Remember me#}
{#                                </label>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-9">
                            <button type="submit" class="btn btn-default" >注 册</button>
                        </div>
                    </div>
                    <div class="form-group text-center">
                        <div class="col-sm-offset-3 col-sm-9">
                            <span>已有账号？<a href="{% url 'myarticle:login' %}">直接登录</a></span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-2 col-sm-2"></div>
        </div>
    </div>
    {% endblock %}
</body>
</html>